import React from 'react';
import {
  Code2,
  ServerCrash,
  Cloud,
  Cpu,
  Layers,
  Workflow,
  LayoutGrid,
  Activity,
  ShieldCheck,
  HardDrive,
  TrendingUp,
  PiggyBank,
  RefreshCw,
  Bot,
  Radio,
  LineChart,
  Database,
  Smartphone,
  Shuffle,
  Headphones,
  Shield,
  Network,
  CloudUpload,
  HardDriveDownload,
  Terminal,
  Orbit,
  GitMerge,
  Lock,
  BarChart3,
  Server,
  Zap,
  CheckCircle2,
  ArrowRight,
  ChevronRight,
  Phone,
  Mail,
  MapPin,
  Clock,
  Sparkles,
  ExternalLink,
  HelpCircle,
  Users,
  Compass,
  ArrowUpRight
} from 'lucide-react';

interface DynamicIconProps {
  name: string;
  className?: string;
}

export const DynamicIcon: React.FC<DynamicIconProps> = ({ name, className = 'w-5 h-5' }) => {
  const icons: Record<string, React.ReactElement> = {
    Code2: <Code2 className={className} />,
    ServerCrash: <ServerCrash className={className} />,
    Cloud: <Cloud className={className} />,
    Cpu: <Cpu className={className} />,
    Layers: <Layers className={className} />,
    Workflow: <Workflow className={className} />,
    LayoutGrid: <LayoutGrid className={className} />,
    Activity: <Activity className={className} />,
    ShieldCheck: <ShieldCheck className={className} />,
    HardDrive: <HardDrive className={className} />,
    TrendingUp: <TrendingUp className={className} />,
    PiggyBank: <PiggyBank className={className} />,
    RefreshCw: <RefreshCw className={className} />,
    Bot: <Bot className={className} />,
    Radio: <Radio className={className} />,
    LineChart: <LineChart className={className} />,
    Database: <Database className={className} />,
    Smartphone: <Smartphone className={className} />,
    Shuffle: <Shuffle className={className} />,
    Headphones: <Headphones className={className} />,
    Shield: <Shield className={className} />,
    Network: <Network className={className} />,
    CloudUpload: <CloudUpload className={className} />,
    HardDriveDownload: <HardDriveDownload className={className} />,
    Terminal: <Terminal className={className} />,
    Orbit: <Orbit className={className} />,
    GitMerge: <GitMerge className={className} />,
    Lock: <Lock className={className} />,
    BarChart3: <BarChart3 className={className} />,
    Server: <Server className={className} />,
    Zap: <Zap className={className} />,
    CheckCircle2: <CheckCircle2 className={className} />,
    ArrowRight: <ArrowRight className={className} />,
    ChevronRight: <ChevronRight className={className} />,
    Phone: <Phone className={className} />,
    Mail: <Mail className={className} />,
    MapPin: <MapPin className={className} />,
    Clock: <Clock className={className} />,
    Sparkles: <Sparkles className={className} />,
    ExternalLink: <ExternalLink className={className} />,
    HelpCircle: <HelpCircle className={className} />,
    Users: <Users className={className} />,
    Compass: <Compass className={className} />,
    ArrowUpRight: <ArrowUpRight className={className} />
  };

  return icons[name] || <Sparkles className={className} />;
};
